# Generated by Django 5.2.8 on 2025-11-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('review', 'Review')], default='pending', max_length=10),
        ),
    ]
